scan_filter_chain:
- name: box
  type: filters_pkg/LaserScanBoxFilter
  params:
    box_frame: thorvald_001/hokuyo_front
    min_x: -1.0
    max_x: 1.0
    min_y: -1.0
    max_y: 1.0
    min_z: -1.0
    max_z: 1.0